# install_autosync.ps1
# Makes the dengue auto-sync watcher start automatically (hidden) at every
# login. No admin rights needed — it just drops a tiny launcher in your
# Windows Startup folder and starts the watcher now.
#
# To stop auto-start later: delete  DengueAutoSync.vbs  from your Startup folder
#   (Win+R  ->  shell:startup), and end the hidden powershell.exe if running.

$repo    = $PSScriptRoot
$startup = [Environment]::GetFolderPath('Startup')
$vbsDst  = Join-Path $startup 'DengueAutoSync.vbs'

# Generate a launcher that runs the watcher with NO visible window.
$vbs = @"
' Auto-generated by install_autosync.ps1 — launches the dengue auto-sync
' watcher hidden (no console window) at logon.
Set sh = CreateObject("WScript.Shell")
sh.CurrentDirectory = "$repo"
sh.Run "powershell.exe -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ""$repo\watch_and_push.ps1""", 0, False
"@
Set-Content -LiteralPath $vbsDst -Value $vbs -Encoding ASCII
Write-Host "Installed startup launcher: $vbsDst"

# Start it right now too (the single-instance guard prevents duplicates).
Start-Process -FilePath 'wscript.exe' -ArgumentList "`"$vbsDst`""
Start-Sleep -Seconds 3
$p = Get-CimInstance Win32_Process -Filter "Name='powershell.exe'" |
     Where-Object { $_.CommandLine -like '*watch_and_push.ps1*' }
if ($p) { Write-Host "Watcher is running (PID $($p.ProcessId)). It will also auto-start at every login." }
else    { Write-Host "Launcher installed. The watcher will start at your next login (or run sync_now.bat anytime)." }
